# import key
- name: import key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Installing from the APT repositoryedit
  shell: sudo apt-get install apt-transport-https

- name: Save the repository definition
  shell: echo "deb https://artifacts.elastic.co/packages/{{es_version}}/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-{{es_version}}.list

- name: install elasticsearch
  shell: yum install elasticsearch -y